### ISSUE TITLE
how to upload image

### ISSUE THREAD

**Issue by jay8499198** [mr5/icarus-android#1]
when i click image button will  auto  insert an  default image, i can not find this code.
how can i get this event ?
i very like this rich editor~

**Comment by mr5** [comment]
`image` and `link` button need user's actions, so they have a method named `popover`, it be invoked when editor need a user action, it has two params: `params` and `callbackName`, `params` mean previous data, `callbackName` is callback, tell  the new data to editor.

``` java
     getIcarus().jsCallback(callbackName, image, Image.class);
```

 You can override it for yourself logics, see https://github.com/mr5/icarus-android/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fmr5%2Ficarus%2Fbutton%2FImageButton.java#L45

Logics of uploading images to server must be implemented by yourself.

If you like it, star it please 😄
