### ISSUE TITLE
如何自定义Toolbar上面图标的状态

### ISSUE THREAD

**Issue by RedStartGong** [mr5/icarus-android#10]
在使用的时候可能需要修改Toolbar的图标，不知道该如何切换各个图标的状态

**Comment by mr5** [comment]
具体的图标是由你自己控制的，每个图标都是个 TextView，你可以使用自己的 typeface 来改变特定的图标。建议了解一下 iconfont。

**Comment by mr5** [comment]
按钮有四种状态：
enabled：true/false 可用/不可用；不可用时默认会禁用该按钮的 click 事件；
activated：true/false 激活/未激活；激活时默认行为是高亮该按钮；

这四种状态为自动帮你判断，并且在状态变更时会通过 `button` 的以下方法传递，默认会帮你变更颜色；

``` java
    public void setEnabled(boolean enabled);
    public void setActivated(boolean activated);
```

see https://github.com/mr5/icarus-android/blob/master/library/src/main/java/com/github/mr5/icarus/button/TextViewButton.java#L98-L105

**Comment by RedStartGong** [comment]
好的，谢谢
