### ISSUE TITLE
有图片网址，怎么插入

### ISSUE THREAD

**Issue by mengliyuxuan** [mr5/icarus-android#11]
现在看demo点击图片的时候插入的是默认的图片，然后点击图片会弹出对话框，让输入链接，能修改图片，怎么能直接插入自己想插入的图片，且图片style:width=100%，铺满

**Comment by mr5** [comment]
提供了 insertHtml 方法可以插入任意标签到当前选区

``` java
icarus.insertHtml("<img src=\"xxx\" style=\"width:100%\">");
```

**Comment by oldfeel** [comment]
@mr5 我用 insertHtml 插入图片后,再用 getContent 获取内容时发现 style 不见了.但是起作用.
android: 5.0.1

**Comment by mr5** [comment]
@oldfeel 

为了安全和防止用户拷贝的样式中含样式导致错乱，默认对有属性白名单机制过滤掉不在白名单的属性，如果需要允许指定标签的指定属性有效，可以通过 `Options` 的 `addAllowedAttributes` 来设置

https://github.com/mr5/icarus-android/blob/master/library/src/main/java/com/github/mr5/icarus/entity/Options.java#L76

如允许 img 标签的 style 和 class

``` java
options.addAllowedAttributes("img", Arrays.asList("style", "class"))
```

**Comment by oldfeel** [comment]
@mr5 好的,谢谢
