### ISSUE TITLE
How can I disable the editing function. 

### ISSUE THREAD

**Issue by xiaoyifan** [mr5/icarus-android#12]
Hi!! As the issue named, I want to use the same set of layout style in another view to display what I just typed in. Is there a way I can disable the cursor and toolbar, so the editor just looks like a text view?

**Comment by mr5** [comment]
The best way to display rich text is using WebView. Make a new WebView in 'another view', then invoke the `loadData` method in WebView class.

See https://developer.android.com/reference/android/webkit/WebView.html#loadData(java.lang.String, java.lang.String, java.lang.String)

**Comment by mr5** [comment]
Stylesheet file:
 https://github.com/mr5/icarus-android/blob/master/library/src/main/assets/icarus-editor/styles/simditor.css

**Comment by xiaoyifan** [comment]
great! thanks! I'll have a try!
