### ISSUE TITLE
Add your own button and function to it

### ISSUE THREAD

**Issue by long1eu** [mr5/icarus-android#15]
Do you think is it possible to add my own button ?

**Comment by mr5** [comment]
Yes, it is possible.
If you want to add your own button and implement it by Java,  just implement the interface named [`Button` ](https://github.com/mr5/icarus-android/blob/master/library/src/main/java/com/github/mr5/icarus/button/Button.java), then add it to Toolbar

icarus-android base on Simditor, so you cant implement buttons by Javascript too. See the  [Simditor docs](http://simditor.tower.im/docs/doc-usage.html)

**Comment by long1eu** [comment]
Thanks for you detailed answer. It want to a a button that creates a custom
tag and sets color to a the selected text.

2016-09-10 8:13 GMT+03:00 Dyson Woo notifications@github.com:

**Comment by mr5** [comment]
It is awesome.  You can create a pull request after you finished it, if you don't mind.

**Comment by long1eu** [comment]
The docs are not very specific and I'm a begginer at js. Sorry. I will try
another repository.

2016-09-10 8:26 GMT+03:00 Dyson Woo notifications@github.com:
