### ISSUE TITLE
如果我想输出这种格式的文本应该怎么弄

### ISSUE THREAD

**Issue by Swordce** [mr5/icarus-android#16]
![image](https://cloud.githubusercontent.com/assets/16829238/18939966/157359a0-8637-11e6-8b38-aa0d76dcf268.png)

**Comment by mr5** [comment]
是要输出 HTML 实体还是？
如果想输出 HTML 实体，转义后通过 `insertHtml` 方法插入即可。
如果想作为 DOM 插入，class 属性被过滤，参考属性白名单，将 `class` 加为白名单即可不被过滤：

https://github.com/mr5/icarus-android#allowedattributes-mapstring-liststring

**Comment by Swordce** [comment]
就是输入一段文字，获取文字的时候可以直接获得这种格式的数据

**Comment by Swordce** [comment]
help!

**Comment by Swordce** [comment]
Help
预期效果：
![image](https://cloud.githubusercontent.com/assets/16829238/19216849/630a8cf4-8dff-11e6-9fd5-8876e811bd94.png)
实际效果：
![image](https://cloud.githubusercontent.com/assets/16829238/19216855/b8981524-8dff-11e6-9c85-2acf020e086b.png)

使用的代码：

![image](https://cloud.githubusercontent.com/assets/16829238/19216859/ddd7fbec-8dff-11e6-951e-7a204fbb4364.png)

**Comment by mr5** [comment]
一个斜杠就好了，目的是针对 Java 字符串进行转义（最终字符串没斜杠），或者使用单引号包裹 HTML 属性值。你的写法最终输出的就是有反斜杠，当然无法渲染。

``` java
icarus.setContent("<p class=\"xxxx\">");
```

上面这种写法可以在外面写好正常的 HTML 代码，然后粘贴的时候让 IDE 自动帮你加反斜杠，不建议自己加。

不写反斜杠：

``` java
icarus.setContent("<p class='xxxx'>");
```
