### ISSUE TITLE
增加setHtml和getHtml方法

### ISSUE THREAD

**Issue by hongyangAndroid** [mr5/icarus-android#17]
测试发现，一段html文本：

```
<h1>正则表达式</h1><p>&nbsp; &nbsp; &nbsp; <span style="text-decoration: underline;">正则表达式</span>，又称规则表达式。（英语：<em>Regular Expression</em>，在代码中常简写为regex、regexp或RE），计算机科学的一个<strong>概念</strong>。正则表通常被用来检索、替换那些符合某个模式(规则)的文本。
```

通过setContent插入，span的`style="text-decoration: underline;`无法生效。
而通过insertHTML插入则正常，但是会默认选中一堆文字。

此外getContent方法也会造成一些`style="text-decoration: underline;`类的样式丢失。

是否能够增加setHtml和getHtml方法，满足此需求。

**Comment by mr5** [comment]
为了安全考虑默认不允许设置属性，可以通过设置打开，文档：
https://github.com/mr5/icarus-android#allowedattributes-mapstring-liststring

**Comment by hongyangAndroid** [comment]
```
options.addAllowedAttributes("span", Arrays.asList("style","class"));
```

添加该行代码，上述的文本，下划线依然无法显示。

**Comment by hongyangAndroid** [comment]
查看js文件，发现应该在此配置：

```
 this._allowedStyles = $.extend({
      span: ['color', 'font-size','text-decoration'],
    }
```

目前移除`Formatter.prototype._cleanNodeStyles`逻辑，暂时正常。

如果有潜在问题，请告知。
