### ISSUE TITLE
 您好 请问如何进文本插入数据库？

### ISSUE THREAD

**Issue by ghost** [mr5/icarus-android#22]
类似记事本那种，编辑好文本好保存数据库 可是会把哪些段落标签也给保存进去，有没有提供这种格式转换的类？

**Comment by mr5** [comment]
这是富文本编辑器，作用就是所见即所得的形式编辑 HTML 富文本，保存到数据库中的数据当然是 HTML 格式的，即使你不用 HTML 你也得自创一套编码吧，否则那些文字本身以外的东西怎么描述？如果你不需要编辑带格式的文本，直接使用 `EditText` 即可，不需要使用这个编辑器。
