### ISSUE TITLE
是否有icarus.setContent（）成功以后的回调

### ISSUE THREAD

**Issue by ghost** [mr5/icarus-android#24]
当调用setContent 之后会有短暂的时间在加载内容，会有一片空白
 建议作者添加一个成功以后的回调这样可以在加载中添加一个loading的动画

**Comment by mr5** [comment]
试试 `runAfterReady ` 方法，用 `Runnable` 封装关闭 loading 的逻辑传进去，这个回调队列会在 `WebView`  `onPageFinished` 时执行，但这个不一定靠谱。目前没有找到渲染回调的方法，不行的话，可以考虑写死一个 loading，根据内容长度决定 loading 的时长。

**Comment by ghost** [comment]
谢谢 !
