### ISSUE TITLE
有没有办法更改字体？

### ISSUE THREAD

**Issue by willbe058** [mr5/icarus-android#4]
不知道Webview有办法么

**Comment by mr5** [comment]
参考 [默认 CSS 文件](https://github.com/mr5/icarus-android/blob/master/library/src/main/assets/icarus-editor/styles/simditor.css) 编写你自己的 CSS 文件来覆盖默认样式

icarus 提供了 loadCSS 方法：

``` java
icarus.loadCSS("file:///android_asset/xxx.css");
```

> 编辑器主节点的 class name 为 simditor-body

**Comment by willbe058** [comment]
谢谢，但是现在还有一个问题，在webview中编辑时其内容会被缩放，如果不希望webview中编辑内容可以被左右拖动呢？

**Comment by mr5** [comment]
「被缩放」应该是指内容过宽导致页面被横向撑开出现滚动条编辑器区域可以左右拖动吧，这个问题我记得有特意处理过，我们自己使用时也没有出现这个情况 。

具体是什么内容把页面撑开了呢，截个图和提供下安卓版本号我看下。

**Comment by willbe058** [comment]
情况是在webview render完成后，点击编辑区域，其中内容会被放大一点，导致可以左右滑动了。不过我把editor.html里的viewport元素内容加一个user-scalable=no就好了

**Comment by mr5** [comment]
赞。我还真忘了加这个  -  -

**Comment by willbe058** [comment]
😄我也是因为有这个需求查到的，非常不错的rich editor～

**Comment by mr5** [comment]
fixed.
