### ISSUE TITLE
could not find com.github...

### ISSUE THREAD

**Issue by lyuruiyue** [mr5/icarus-android#6]
在build.gradle中加入compile 'com.github.mr5:icarus:0.1.14-SNAPSHOT'后报错
Error:Could not find com.github.mr5:icarus:0.1.14-SNAPSHOT.

**Comment by mr5** [comment]
SNAPSHOT 版本的库需要添加 SNAPSHOTS 仓库到 repositories 配置段

``` groovy
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
```

我把  0.1.14 release 了，去掉 `-SNAPSHOT` 即可，不加上面的配置也可以。

**Comment by lyuruiyue** [comment]
![capture](https://cloud.githubusercontent.com/assets/17601185/16019845/32d7e24e-3179-11e6-9d97-e323747897fa.PNG)
不配置maven的情况下还是不行啊

**Comment by mr5** [comment]
这两个仓库有没有添加？

``` groovy
mavenCentral()
jcenter()
```

**Comment by lyuruiyue** [comment]
在project和module里的 repositories里都加了 mavenCentral()和jcenter()后还是不行...

**Comment by mr5** [comment]
已修复，因为 release 之后没有同步到 maven central，由于我本地有 mavenLocal() 导致在我自己电脑上无法重现。重试即可
