### ISSUE TITLE
插入图片问题

### ISSUE THREAD

**Issue by zaaach** [mr5/icarus-android#7]
怎么让图片单独占一行并且居中，这个图片可以是上传之后的图片链接吗

**Comment by mr5** [comment]
1. 默认地，图片是插入到光标所在区域。如果需要特殊处理可以通过 `icarus.insertHtml()` 方法来手动插入 HTML 代码：

```
<p style="text-align: center;"><img src="xxxx.jpg"></p>
```
1.  富文本编辑器是管理富文本的，图片只是一个 img 标签，你可以放任何图片地址，上传图片后让服务器端返回你一个图片地址即可。

**Comment by gewuxy** [comment]
我在img中设置style="max-width:100%"，最后getContent返回中丢失了？
