### ISSUE TITLE
无法compile

### ISSUE THREAD

**Issue by lvtanxi** [mr5/icarus-android#8]
Error:(26, 13) Failed to resolve: com.github.mr5:icarus:0.1.14

**Comment by mr5** [comment]
这两个 repository 有添加吗

``` groovy
mavenCentral()
jcenter()
```

**Comment by lvtanxi** [comment]
都添加了的，始终无法compile成功

**Comment by mr5** [comment]
提供一下更详细的报错信息

**Comment by mr5** [comment]
另外，提供一下项目的 gradle 配置信息，我看下能否重现。

**Comment by mr5** [comment]
已修复，因为 release 之后没有同步到 maven central，由于我本地有 `mavenLocal()` 导致在我自己电脑上无法重现。重试即可
